"""Editorial second pass on the body candidate; no solver/data modifications."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / 'integration/body-candidate.tex').read_text(encoding='utf-8')
lines = source.splitlines()
changes = {
    'The study examines whether matching one melt-pool length': r'''The analysis connects surface-length calibration, fusion-zone shape and the rear phase interval through two complementary comparisons. A source factor fitted to condition B length is retained for all three operating conditions and for width and depth. At B, independent changes in the high-temperature conductivity and sensible-storage continuations resolve their contributions to the calibrated field. Rear solidus and liquidus positions then separate thermal-tail displacement from phase-span change, while scan speed converts the spatial interval to material passage time.''',
    'For the four B corners, power, speed': r'''The four B corners share power, speed, beam, density, phase thresholds, latent heat, mesh, observation operators and the source factor of the LL calibration. The first letter denotes conductivity and the second sensible specific heat. Sharing B=LL between the operating-condition and continuation comparisons gives six production solutions.''',
    'Nominal experimental length increases by 11': r'''Nominal experimental length increases by 11~\um\ from B to C, whereas model length decreases by 38.53~\um. The two reported expanded-uncertainty scales give a zero-correlation quadrature of 38.89~\um, larger than the nominal experimental change. This descriptive comparison limits interpretation of the sign of that experimental trend; C's individual discrepancy concerns its own reference mean. Retained axial changes below 0.37~\um\ are much smaller than the main B/C residuals, indicating that further refinement in that direction would leave the principal shape discrepancy largely intact.''',
    'At 1320~$^\\circ$C, conductivity changes': r'''At 1320~$^\circ$C, conductivity changes from 32.51 to 25.20~\si{\watt\per\metre\per\kelvin} under holding, a reduction of 22.48\%. Sensible specific heat decreases from 721.13 to 670~\si{\joule\per\kilogram\per\kelvin}, or 7.09\%. With latent storage included, effective specific heat decreases from 5387.79 to 5336.67~\si{\joule\per\kilogram\per\kelvin}, or 0.95\%, and enthalpy from the cold reference decreases by 0.66\%. The property changes therefore perturb transport and storage by different amounts in the adopted mushy interval. The median axial-face P\'eclet diagnostic rises from 4.44 in LL to 5.77 in HL, indicating a changed balance of diffusion and coordinate enthalpy transport on the selected faces. Integrated outward diffusion from the rear hot region also rises, from 14.724 to 14.913~W. Both the gradients and the temperature-selected integration boundary change with the solution, so this regional flux requires interpretation together with its moving spatial population. The conductivity branch also changes surface recovery through the corresponding material primitive.''',
    'The current-mesh depth contrast illustrates cancellation': r'''The current-mesh depth contrast illustrates cancellation. Conductivity holding changes depth by $-1.03$~\um; heat-capacity holding contributes +0.49~\um\ and the interaction +0.21~\um, leaving a net $-0.32$~\um. Conductivity effects remain negative at both storage levels ($-1.03$ and $-0.82$~\um), while storage effects remain positive at both conductivity levels (+0.49 and +0.71~\um). All corners retain the B width excess and depth deficit. The continuation choices thus change the tail substantially while preserving the principal fusion-shape discrepancy. The 34--43~\um\ length response exceeds the retained baseline axial sensitivity by a wide margin; the 0.04~\um\ width interaction remains an unresolved fine-scale comparison pending branch-specific refinement.''',
    'The length fit constrains one combination': r'''The length fit constrains a combination of source strength, material continuation and observation mapping. The retained B width excess and depth deficit, together with the B--C shape response, locate its remaining discrepancy in transverse heat distribution and penetration (Fig.~\ref{fig:comparison}). Surface length supplies one constraint on this field; fusion shape and temperature trajectories supply additional information. Source representation, transport closure and the relation between radiance-derived and temperature-threshold boundaries therefore enter the assessment as distinct contributors.''',
    'Keeping the calibrated source fixed reveals opposing': r'''Keeping the calibrated source fixed separates opposing property responses. Conductivity holding extends the pool at either storage setting, while sensible-storage holding shortens it at either conductivity setting (Table~\ref{tab:factorial}). Their combination gives a 34.28~\um{} length increase. The rear profiles locate the dominant response: the rear solidus accounts for 98.3\% of the conductivity-induced extension, and the liquidus moves almost the same distance. These paired displacements shift the thermal tail relative to the source while leaving a comparatively stable phase separation (Fig.~\ref{fig:factorial}). The width excess and depth deficit persist across the four corners, separating this tail sensitivity from correction of the fusion shape.''',
    'A discriminating thermal test would retain': r'''The comparisons identify complementary evidence for the next assessment. A defined source and observation mapping, tracks or profiles reserved before fitting, and an independently measured temperature trajectory would test the calibrated field together with its width and depth. Composition- and state-matched high-temperature data would constrain the material continuation. Each observation addresses a different part of the interpretation: fusion shape assesses energy redistribution, rear boundaries locate the phase interval, and a temperature history assesses its passage in material time. The present fixed-source contrasts supply this separation within the assumed conduction balance.''',
    'Geometric calibration provides a useful constraint on thermal modeling': r'''Geometric calibration is useful for low-cost thermal modeling of laser processing, while its physical assessment requires the observables carried by the fitted field to be distinguished. In the present IN625 enthalpy calculation, a close surface-length fit coexists with a wider and shallower fusion envelope than the reference means. The fixed-power speed comparison further exposes a discrepancy in the balance between transverse contraction and penetration. Fusion shape consequently provides an assessment of energy redistribution beyond the fitted axial extent.''',
    'The fixed-source property contrast separates opposing responses that': r'''Independent continuation contrasts reveal how high-temperature transport and storage assumptions contribute to that field. Conductivity holding extends the pool and sensible heat-capacity holding shortens it at both tested factor levels, giving a joint length increase of 34.28~\um{}. Rear solidus and liquidus translation dominates the conductivity response, while their separation changes comparatively little. The principal sensitivity therefore concerns the location of the thermal tail; the retained width/depth discrepancy calls for additional source, transport and observation evidence.''',
    'Spatial phase separation and material cooling time must also': r'''Material cooling time adds a further constraint to this spatial interpretation. Almost equal rear phase spans at 0.8 and 1.2~m/s correspond to a roughly one-third reduction in passage time and a 49.02\% increase in the modeled interval-mean cooling rate. The relation follows from passage through the same quasi-steady field and defines a derived centerline history. Taken together, the comparisons distinguish fusion shape, tail position and material time as complementary targets for thermal-model assessment. Credible high-temperature material data and a temperature trajectory aligned with the source, phase interval and observation definitions would establish their physical correspondence.''',
}
records = []
for prefix, replacement in changes.items():
    found = [i for i, line in enumerate(lines) if line.startswith(prefix)]
    if len(found) != 1:
        raise ValueError((prefix, len(found)))
    i = found[0]
    records.append({'line_before_integration': i + 1, 'before': lines[i], 'after': replacement,
                    'purpose': 'Develop the observed relation and its assessment consequence in objective prose.'})
    lines[i] = replacement

caption_changes = {
    'No branch is recalibrated. Rounded geometry': 'All branches retain the LL-fitted source factor. Rounded geometry',
    'Factorial effects are deterministic finite contrasts, not statistical effect estimates.': 'Factorial effects describe deterministic finite contrasts between continuation functions.',
    'The fields are model outputs, not microscopy or inferred liquid-flow maps. Both panels': 'Both panels display calculated thermal geometry and',
    'The model histories share one steady solution and should not be counted as independent validation observables.': 'Spatial spans and passage times are transformations of the same steady centerline field.',
    'Interval-mean cooling rates discussed in the text are derived over 1350--1290~$^\\circ$C; they are not plotted here.': 'The text reports the corresponding interval-mean cooling rates over 1350--1290~$^\\circ$C.',
    'beam representation, phase law, parameter calibration and observation definitions differ, so this is not a controlled ranking of solvers.': 'their beam representations, phase laws, calibration targets and observation definitions set the respective comparison scope.',
}
updated = '\n'.join(lines) + '\n'
for before, after in caption_changes.items():
    if updated.count(before) != 1:
        raise ValueError((before, updated.count(before)))
    updated = updated.replace(before, after)
(ROOT / 'integration/body-candidate.tex').write_text(updated, encoding='utf-8')
(ROOT / 'integration/second-pass-changes.json').write_text(json.dumps(records, indent=2) + '\n', encoding='utf-8')
print('Refined', len(records), 'paragraphs and', len(caption_changes), 'caption passages.')
