"""Create reader-facing body prose from the frozen R3 text; root integrates later."""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[1]
source=(ROOT/'manuscript-input.tex').read_text(encoding='utf-8')
lines=source.splitlines()
changes={
'The experimental comparison uses constant-speed laser scanning':r'''The benchmark comprises constant-speed single-track laser scans on bare IN625 plate under three public AMMT conditions (Table~\ref{tab:conditions}). Conditions B and C share the same nominal power and isolate a speed change; condition A combines a lower power with a lower speed. The measured beam diameter is $D_{4\sigma}=170$~\um{}~\cite{lane2020}. The normalized circular Gaussian used here has $D_{4\sigma}=2w$, giving $w=85$~\um. This reconstruction represents the measured second-moment diameter with circular symmetry, while the published measurement retains the two-dimensional beam map.''',
'The length reference is the AMMT condition mean':r'''Length references are the AMMT condition means reported by Lane et al.~\cite{lane2020}. Width and depth references are the NIST challenge Table~2 means for the 100~\us-track microscopy classes~\cite{nist2018}. Lane's later cross-section analysis combines the 100 and 20~\us{} classes. Imaging length and metallographic cross sections consequently represent separately sampled condition-level populations. Their individual means provide the geometric comparisons used throughout the study.''',
'The comparisons are retrospective and nonblind':r'''The published geometric targets were consulted during model development. The calibration objective contains the condition B length; the resulting source factor is retained for B width/depth and for all condition A and C comparisons. Expanded uncertainties $U$ with coverage factor $k=2$ are taken from Lane's uncertainty budgets. For width and depth, these scales belong to the published combined-class microscopy analysis, whereas the means used here belong to the NIST 100~\us{} classes. Signed deviations $\delta$ are reported individually as $\delta/U$ relative to the corresponding published measurement scale. This reporting preserves the separate provenance of the mean and uncertainty and leaves model, input and calibration uncertainty outside the denominator.''',
'Each $\\xi$ slice is first reconstructed':r'''Each $\xi$ slice is reconstructed at the surface and symmetry plane, bilinearly interpolated onto observation coordinates, and then maximized over passage. This order defines the interpolated fusion envelope; maximizing nodal temperatures before interpolation gives a different envelope. Width is twice the positive-$y$ extent and depth is the negative of the lowest $z$. The observation pitch controls sampling of the reconstructed geometry. Figures label the surface length proxy $L_s$ and fusion-envelope extents $W_f$ and $D_f$; these correspond to $L$, $W$ and $D$ in the text.''',
"Lane's imaging length uses":r'''Lane's imaging length uses a radiance-profile second-derivative minimum for the rear solidification location and a calibrated front threshold~\cite{lane2020}. The model uses two solidus crossings of a recovered temperature field. The imaging procedure includes emittance, exposure and viewing effects through its radiance measurement; the temperature-threshold operator supplies the model boundary. The fitted $\eta$ therefore belongs to the selected source, material law and boundary definition. Fusion-envelope width and depth are compared with metallographic measurements.''',
'These quantities describe stationary material':r'''These quantities characterize stationary material passing through the quasi-steady field. At a fixed laboratory point, $\mathrm d\xi/\mathrm dt=-v$, so the spatial interval and scan speed determine both the passage time and the interval-mean cooling magnitude. Constant-speed space-to-time mapping is also used in the AMMT measurements~\cite{lane2020}; their cooling analysis uses a below-solidus interval, while the present calculation uses 1350--1290~$^\circ$C. The three quantities in Eq.~\eqref{eq:passage} share the same modeled temperature field.''',
'The conditional conductivity effect at held':r'''The conditional conductivity effect at held $c_p$ is $Q_{\HH}-Q_{\LH}=\delta_k+I_{k,c_p}$; the conditional storage effect at held $k$ is $Q_{\HH}-Q_{\HL}=\delta_{c_p}+I_{k,c_p}$. Reporting both conditions establishes whether the response direction persists across the two factor levels. The effects are deterministic differences between prescribed continuation functions within one physical model.''',
'An axial-face P':r'''An axial-face P\'eclet diagnostic compares coordinate enthalpy transport with diffusion in the phase interval. A discrete rear hot-region budget measures net outward diffusive power. Each branch defines its temperature-selected region separately, allowing the diagnostic population and region boundary to follow the solved field. These budgets complement the matched-coordinate phase thresholds; their definitions are given in the appendix.''',
'A separate constant-property moving-Gaussian problem':r'''A separate constant-property moving-Gaussian problem checks source integration, frame transport and geometric extraction against a semi-infinite analytical reference. This verification isolates numerical implementation from assessment against physical measurements~\cite{oberkampf2002}. Its reference $L/W/D$ is $407.535/153.293/34.836$~\um; finite-volume differences are +0.139\%, +0.190\% and $-0.499$\%, respectively. The benchmark uses constant properties and omits phase change, making its accuracy assessment specific to that verification problem.''',
'The one-target calibration reproduces':r'''The length calibration gives 359.16~\um{} at B and leaves a systematic width/depth residual at B and C (Table~\ref{tab:geometry} and Fig.~\ref{fig:comparison}). The B width exceeds the nominal reference by 19.54~\um{} and depth falls below it by 4.88~\um, giving separate expanded-uncertainty-scale ratios of +3.10 and $-1.23$. A closely matched axial length thus coexists with an over-wide, shallow fusion envelope.''',
'A differences are smaller':r'''Condition A deviations are smaller than their respective reported measurement-uncertainty scales. In C, the model is 49.37~\um{} shorter, 23.05~\um{} wider and 7.56~\um{} shallower than the nominal references. The predicted aspect ratios $W/D=3.79,4.60,5.85$ for A/B/C also show the wide/shallow pattern, compared with condition-level reference ratios 3.48,3.43,3.58. These reference ratios are calculated from separately sampled class means.''',
'At fixed power from B to C':r'''At fixed power from B to C, a 50\% speed increase reduces absorbed line energy by one third. Model width decreases by 9.78\% and depth by 29.16\%; the nominal reference changes are 14.17\% and 17.78\%. The modeled $W/D$ increases by 27.36\% from B to C. The discrepancy therefore involves both absolute dimensions and the balance between transverse contraction and penetration. Condition A also changes power, so the B--C pair provides the fixed-power speed comparison.''',
'The heat-capacity response and interaction offset':r'''The heat-capacity response and interaction offset part of the conductivity response, revealing the competing contributions within the LL-to-HH difference. The signs persist at the other factor level: conductivity holding increases length by 40.45~\um{} when $c_p$ is held, and storage holding decreases length by 8.93~\um{} when $k$ is held. Conductivity holding therefore extends the tail and storage holding shortens it at both tested factor levels.''',
'Conductivity holding moves the rear':r'''Conductivity holding moves the rear solidus and liquidus by $-42.49$ and $-43.50$~\um, while the front solidus moves by +0.73~\um. Rear solidus displacement accounts for 98.3\% of the conductivity-induced length increase, with the front contributing 1.7\%. The rear phase span changes by $-1.01$~\um. Heat-capacity holding moves the rear positions forward by +6.22 and +6.53~\um, changing their separation by +0.31~\um. The large length response predominantly translates the two rear phase boundaries together, while their separation remains comparatively stable.''',
'The operating-condition comparison therefore':r'''The fixed-power speed comparison distinguishes two responses of the modeled field: contraction of the fusion envelope and faster passage through the rear phase interval. Width and depth are compared with the condition-level metallography; the passage calculation characterizes the associated centerline temperature history.''',
'Geometric agreement can conceal thermal differences':r'''The information carried by geometry and temperature has also been separated experimentally. Bare-plate 316L calculations fitted several Fresnel/accommodation parameter combinations to cross-sectional area and width-to-depth ratio, producing different surface-temperature profiles; two-color measurements narrowed the acceptable combinations~\cite{myers2023}. That study varied fitted parameter combinations, whereas the present continuations retain the source factor of the LL length fit. Their contrast measures material-function response after a common calibration. Together these designs show the distinct roles of geometric fitting and temperature information in assessing a model.''',
'The closest AMMT comparison also':r'''The closest AMMT study achieved improved A/C geometry by combining measured laser input with effective directional conductivity calibrated at B~\cite{kollmannsberger2019}. Its authors treated internal melt-pool temperatures as a separate assessment problem. The measured source and directional closure provide a physically motivated comparison with the present isotropic Gaussian calculation. Retaining a common source and transport structure here isolates the response to the high-temperature material continuation.''',
'The effective-heat-capacity representation separates':r'''The effective-heat-capacity representation separates latent and sensible storage~\cite{vanelsen2007}. In the adopted phase interval, latent heat contributes 4666.67~\si{\joule\per\kilogram\per\kelvin} to effective specific heat. The 7.09\% sensible-$c_p$ reduction at 1320~$^\circ$C consequently becomes a 0.95\% change in latent-inclusive effective specific heat and a 0.66\% change in enthalpy from the cold reference, compared with the 22.48\% conductivity reduction at the same temperature. This energy accounting explains the unequal local perturbation sizes applied to transport and storage. All branches retain the same latent heat; changing sensible heat capacity also changes pre-melting enthalpy and the temperature--enthalpy inverse because its continuation begins below the solidus.''',
'The diagnostics support a changed balance':r'''Conductivity holding changes the local transport balance and the temperature gradients together. The selected axial-face P\'eclet diagnostic increases, and the integrated rear-region conductive power also increases (Section~\ref{sec:property-results}). The latter is evaluated over a temperature-selected boundary that moves with the solution, providing a counterexample to equating a smaller conductivity with lower integrated outward power from that region. Surface recovery changes consistently through $K(T)$ and its inverse. The resolved tail displacement thus combines the field response and the threshold-recovery operator. A matched-region flux comparison or separation of field and recovery contributions would distinguish their respective roles.''',
'Rear-boundary location, phase separation and material time':r'''Rear-boundary location, phase separation and material time describe different aspects of the calibrated field. The B/C rear phase spans are 80.26 and 80.79~\um{}, while passage times are 100.33 and 67.33~\us{} as scan speed rises from 0.8 to 1.2~m/s (Fig.~\ref{fig:trends}). Nearly unchanged spatial separation therefore accompanies a much shorter material interval. The 49.02\% increase in interval-mean cooling magnitude is another expression of the same threshold-and-speed relation in Eq.~\eqref{eq:passage}. Conversely, translating both rear boundaries together changes overall pool length while preserving nearly the same material passage interval at a fixed speed.''',
'Thermography distinguishes these questions experimentally':r'''Spatial profiles and material temperature histories also have distinct measurement roles. Thermography has resolved centerline profiles together with fixed-location temperature histories through scan pulses and turn events~\cite{hooper2018}. The AMMT analysis converts position to time at a known constant speed, using a below-solidus temperature interval and its radiance-based boundary definition~\cite{lane2020}. Aligning a measured trajectory with the present 1350--1290~$^\circ$C calculation would require the same temperature interval and explicit treatment of scan position, exposure and observation mapping.''',
'The passage transformation describes stationary material crossing':r'''The passage transformation follows stationary material crossing the assumed steady field. Fluid motion adds another path through the thermal field: calculations for a Ni--20Cr dispersion-strengthened alloy produced narrower near-surface temperature peaks and hotter subsurface excursions than the corresponding unmodified conduction histories~\cite{Hou2024Dissolution}. This distinction links thermal-field assessment to the trajectories used in microstructure models. A separate transient-conduction study connected geometry verification, solidification-condition calculations and an experimental grain-structure comparison for AlSi10Mg laser and IN718 electron-beam cases~\cite{Plotkowski2017Rapid}. It also showed interface velocities governed by hatch progression in overlapping multi-line melts. The present $v$-based conversion applies to a straight, quasi-steady track and characterizes its centerline passage interval; flow-dependent paths and grain/segregation predictions require their corresponding physical descriptions and measurements.''',
'The shape residual does not identify':r'''Source distribution and effective transport remain competing explanations for the shape residual. A dynamic volumetric source calibrated on bare IN625 tracks at 195~W and 800~mm/s across several spot sizes was subsequently applied to a layer case~\cite{dynamic2024}. The source adjusts its depth and effective absorption with the local melt-pool state, while its phase-dependent properties and 1410~K eutectic endpoint differ from the present interval. Matching the beam, phase assumptions, calibration target and geometry operators would make source redistribution and material closure directly comparable. Replaying the imaging operator would first quantify the effect of radiance-derived boundaries on the fitted source factor.''',
'Two physical limits govern the thermal interpretation':r'''High-temperature material data and omitted liquid-state processes bound the physical use of these sensitivities. The supplier tables end at 982~$^\circ$C for $k$ and 1093~$^\circ$C for $c_p$~\cite{specialmetals625}; L/H extends them by two prescribed rules. Composition-based estimates include IN625 conductivity and identify limited underlying liquid-state data~\cite{mills2006}, providing candidates for a material-specific comparison. The present conduction balance also omits evaporation, melt flow and surface evolution. Its LL, HL, LH and HH positive-$y$ surface-sample peaks are approximately 2697, 3507, 2756 and 3721~$^\circ$C. The extreme held-conductivity temperatures make the absent liquid-state processes consequential; those peaks serve as sensitivity outputs of the assumed balance, while independent thermal measurements are needed to establish their physical credibility.''',
'Numerical checks support the larger responses':r'''The numerical evidence distinguishes the scale of the main response from that of the fine interactions. The 34--43~\um{} length changes exceed the inspected baseline axial sensitivity; resolving submicrometre interactions would require branch-specific three-dimensional refinement. The analytical benchmark, energy balance and solution correction assess numerical execution. Physical comparison additionally depends on the calibration history, separately sampled length and cross-section populations, and source-specific measurement-uncertainty scales described in Section~2.1.'''
}
records=[]
for prefix,replacement in changes.items():
    matches=[i for i,x in enumerate(lines) if x.startswith(prefix)]
    if len(matches)!=1:
        raise ValueError((prefix,len(matches)))
    i=matches[0];records.append({'frozen_line':i+1,'before':lines[i],'after':replacement,'purpose':'State the actual relation/process and keep consequential scope at its interpretation point.'});lines[i]=replacement
(ROOT/'integration/body-candidate.tex').write_text('\n'.join(lines)+'\n',encoding='utf-8')
(ROOT/'integration/objective-prose-changes.json').write_text(json.dumps(records,indent=2)+'\n',encoding='utf-8')
print('Produced',len(records),'semantic paragraph revisions; no numerical inputs changed.')
