from pathlib import Path
import json

ROOT=Path(__file__).resolve().parent
sources={
 'vanelsen2007':dict(title='Solutions for modelling moving heat sources in a semi-infinite medium and applications to laser material processing',doi='10.1016/j.ijheatmasstransfer.2007.02.044',journal='International Journal of Heat and Mass Transfer',year=2007,volume='50',pages='4872–4882',original='pdfs/vanelsen2007.pdf',extract='text/vanelsen2007.txt',read_scope='Author manuscript PDF pp4–5,20–24; governing and enthalpy/phase methods read directly. Page locators below are PDF pages.',metadata='metadata/vanelsen2007-crossref.json'),
 'kollmannsberger2019':dict(title='Accurate Prediction of Melt Pool Shapes in Laser Powder Bed Fusion by the Non-Linear Temperature Equation Including Phase Changes',doi='10.1007/s40192-019-00132-9',journal='Integrating Materials and Manufacturing Innovation',year=2019,volume='8',pages='167–177',original='pdfs/kollmannsberger2019.pdf',extract='text/kollmannsberger2019.txt',read_scope='arXiv1903.09076v1 author preprint pp3–6,9–11; phase law, material constants, source, calibration, anisotropic result and conclusion read directly.',metadata='metadata/kollmannsberger2019-openalex.json'),
 'specialmetals625':dict(title='INCONEL alloy 625',doi=None,journal=None,year=2013,edition='August 2013 bulletin',original='pdfs/specialmetals625.pdf',extract='text/specialmetals625.txt',read_scope='Original supplier bulletin pp1–2, Tables2–3 and footnotes, read directly.',url='https://www.specialmetals.com/documents/technical-bulletins/inconel/inconel-alloy-625.pdf'),
 'dynamic2024':dict(title='A dynamic volumetric heat source model for laser additive manufacturing',doi='10.1016/j.addma.2024.104531',journal='Additive Manufacturing',year=2024,volume='95',pages='104531',original='../../revision-r2/literature/pdfs/dynamic2024.pdf',extract='../../revision-r2/literature/text/dynamic2024.txt',read_scope='Author manuscript pp1–8,17–20 directly read; published identity independently verified by existing Crossref metadata. PDF pages used below.',metadata='../../revision-r2/literature/metadata/dynamic2024-crossref.json'),
 'Plotkowski2017Rapid':dict(title='Verification and validation of a rapid heat transfer calculation methodology for transient melt pool solidification conditions in powder bed metal additive manufacturing',doi='10.1016/j.addma.2017.10.017',journal='Additive Manufacturing',year=2017,volume='18',pages='256–268',original='../../revision-r2/journal/pdfs/vverification2017.pdf',extract='../../revision-r2/journal/texts/vverification2017.txt',read_scope='Author manuscript pp1–8,13–14,18–25 directly read; no longer abstract-only for these claims.',metadata='metadata/Plotkowski2017Rapid-crossref.json'),
 'hooper2018':dict(title='Melt pool temperature and cooling rates in laser powder bed fusion',doi='10.1016/j.addma.2018.05.032',journal='Additive Manufacturing',year=2018,volume='22',pages='548–559',original='../../literature/hooper2018-published.pdf',extract='../../literature/hooper2018-published.txt',read_scope='Published PDF pp10–11 (journal557–558) read directly for spatial/time profiles, latent release and instrument limitations; prior methods reading retained in exemplar-notes.'),
 'Hou2024Dissolution':dict(title='Dissolution zone model of the oxide structure in additively manufactured dispersion-strengthened alloys',doi='10.1016/j.addma.2024.104554',journal='Additive Manufacturing',year=2024,volume='96',pages='104554',original='../../revision-r2/journal/pdfs/dissolution2024.pdf',extract='../../revision-r2/journal/texts/dissolution2024-layout.txt',read_scope='Version-of-record pp1,7–10,18–21 directly read; §4.3 trajectories and AppendixC transformations inspected.',metadata='metadata/Hou2024Dissolution-crossref.json'),
 'mills2006':dict(title='Calculation of Thermophysical Properties of Ni-based Superalloys',doi='10.2355/isijinternational.46.623',journal='ISIJ International',year=2006,volume='46',pages='623–632',original='../../revision-r2/literature/pdfs/mills2006.pdf',extract='../../revision-r2/literature/text/mills2006.txt',read_scope='Published PDF pp1–3,5,7–9 (journal623–625,627,629–631) read directly; IN625 Figure13 and liquid property estimation limits.'),
 'pottlacher2001':dict(title='Thermophysical properties of solid and liquid Inconel 718 alloy',doi='10.1068/htwu340',journal='High Temperatures-High Pressures',year=2001,volume='33',pages='405–410',first_author='Herwig Hosaeus',original=None,extract=None,read_scope='Complete indexed scholarly abstract reconstructed and read; full text not obtained. Do not assign a page passage.',metadata='../../revision-r2/literature/metadata/pottlacher2001-crossref.json',abstract='../../revision-r2/literature/metadata/pottlacher2001-openalex.json'),
 'lane2020':dict(title='Measurements of Melt Pool Geometry and Cooling Rates of Individual Laser Traces on IN625 Bare Plates',doi='10.1007/s40192-020-00169-1',journal='Integrating Materials and Manufacturing Innovation',year=2020,volume='9',pages='16–30',original='Full published HTML previously extracted',extract='../../literature/lane2020-body.txt',read_scope='Existing full-text paragraph extracts P6,P19–36,P42,P69–70 directly read; explicit paragraph locators used.'),
 'myers2023':dict(title='High-resolution melt pool thermal imaging for metals additive manufacturing using the two-color method with a color camera',doi='10.1016/j.addma.2023.103663',journal='Additive Manufacturing',year=2023,volume='73',pages='103663',original='../../literature/myers2023-published.pdf',extract='../../literature/myers2023-published.txt',read_scope='Published PDF p9 Figure8 and plume/observation discussion read directly, with prior Methods/§4.1 full-text reading in exemplar-notes.'),
}

claims=[]
def add(id,anchor,line,claim,key,locator,passage,regime,limits,placement):
    claims.append(dict(id=id,manuscript_anchor=anchor,frozen_line=line,claim_supported=claim,key=key,exact_title=sources[key]['title'],doi=sources[key]['doi'],evidence_level='indexed_abstract' if key=='pottlacher2001' else 'full_text',locator=locator,actual_passage=passage,material_regime_method=regime,limits=limits,placement_or_replacement=placement))

add('C01','The laboratory-frame conduction balance is',84,'Conservative enthalpy treatment combines sensible and latent storage in moving-source conduction.','vanelsen2007','Author PDF p21, Eqs32–35','Both are conservative ways to introduce the latent heat. [...] The effective heat capacity becomes ceff = c + cLf.','Finite-difference moving source, variable properties; subsequently Ti6Al4V examples.','Supports method family and energy accounting, not this FiPy discretization or exact linear phase law. Their Gaussian latent distribution differs.','Introduce Eq(enthalpy) with cite vanelsen2007; cite dynamic2024 separately at phase law. No citation on own analytic inverse.')
add('C02','The equilibrium phase fraction is',90,'A linear liquid/solid-fraction relation across an alloy freezing interval is an existing continuum AM closure.','dynamic2024','Author PDF p5, §2.1 Eq1 and following paragraph','The first source term in Eqn. (1) accounts for the evolution of latent heat during the solid-liquid phase change, applied as a linear temperature-solid fraction relationship across the alloy freezing range.','IN625 continuum conduction, volumetric effective source; constant density, T-dependent k/cp.','Their freezing interval is 1620–1410K and terminates at a nonequilibrium eutectic; this does not establish the current 1290–1350°C law as coupon equilibrium fraction data.','Replace equilibrium phase fraction by adopted linear liquid-fraction closure over the equilibrium melting interval; cite dynamic2024 for closure precedent, specialmetals625 for endpoints.')
add('C03','The adopted constants are',90,'Density8440kg/m3 and melting interval1290–1350°C match the IN625 supplier bulletin.','specialmetals625','Original bulletin p2 Table2','Density [...] gram/cc [...] 8.44; Melting Range [...] °C [...]1290–1350.','Typical general IN625 data, supplier bulletin.','Not coupon-specific density measurements, nonequilibrium solidification path, or a temperature-dependent liquid density.','Put specialmetals625 immediately after rho and Ts/Tl constants, separate from latent source. T0 is study input, no external provenance implied.')
add('C04','the adopted latent heat follows the benchmark modeling setup',98,'Adopted latent heat280000J/kg reproduces an earlier same-benchmark model choice.','kollmannsberger2019','Author preprint p6 Table5','latent heat 2.8e5 [J/kg]; melting temperature interval1290–1350 [°C].','AMB2018-02 IN625 nonlinear phase conduction model; material parameters referenced to supplier/literature.','This is modeling lineage, not a direct latent-heat measurement of current coupon. Their smoothed phase function p3 differs from current piecewise-linear f.','Retain cite directly after latent value/provenance. Do not use this key to claim exact linear f law.')
add('C05','Specific heat and conductivity are linearly interpolated',98,'Actual supplier cp/k endpoints lie below the modeled melting interval; cp is calculated, k measured.','specialmetals625','Original bulletin p2 Tables2–3 and footnotes','Specific Heata [...]2000°F (1093°C) [...] (670); aCalculated. [...] conductivity at982°C=25.2. bMeasurements made at Battelle Memorial Institute; cMaterial annealed2100°F/1hr.','Typical solid IN625, specified annealed material; cp calculation and k measurements have distinct roles.','Does not provide liquid k/cp or validate linear extrapolation or holding. k table has no value at1093°C even though resistivity does.','Retain point-of-use supplier citation in properties paragraph and caption; spell out actual endpoints once, use internal table later.')
add('C06','For a locally quasi-steady translating field',109,'Conduction in source coordinates includes coordinate enthalpy transport.','vanelsen2007','Author PDF pp4–5 Eqs1–4','V [is] the speed of either the heat source or the medium. In most applications, the origin of the coordinate system is fixed to the centre of the heat source [...] the x direction corresponds to the constant speed of a moving heat source.','Constant-speed source, steady limit of energy equation; variable material properties.','Source coordinates/sign conventions differ; current xi=x-vt and divergence form are derived here. No fluid velocity is solved.','Cite modeling context, then explicitly write chain rule -v∂xiH as present derivation; no external citation on algebra identity.')
add('C07','The reported beam diameter is D4sigma=170',62,'170µm D4σ is the measured AMMT beam size.','lane2020','Published full-text §2.1 P6, Table1','For the AMMT, 4-sigma diameter (D4σ) was170µm (full-width half max(FWHM) of100µm).','AMMT bare IN625; measured CCD beam map, different CBM beam.','Diameter is not a literal top-hat width; current circular Gaussian discards measured map structure.','Cite lane2020 at beam diameter in Methods, then derive w=D4σ/2 for the adopted normalized circular Gaussian.')
add('C08','The Gaussian surface input at z=0 is',116,'Normalized radial Gaussian source and its D4σ-to-radius convention have direct AM source-model support.','dynamic2024','Author PDF pp6–7 §2.2.2 Eqs2–3 and Figure2','D4σ represents the ISO standard definition of the laser spot size [...] The areal integral of the radial distribution, A0, ensures that the total absorbed power is represented [...] standard Gaussian profile(k=2).','IN625 AM super-Gaussian surface distribution extended volumetrically; measured spot sizes.','Supports radial normalization convention; does not endorse current surface-only deposition or constant fitted eta. Error-function face integration is derived/code-specific.','Cite after phrase normalized circular Gaussian reconstruction. State w=2σ=D4σ/2=85µm is derived for current q∝exp(-2r²/w²).')
add('C09','Latent-inclusive storage helps explain',322,'Effective heat capacity contains a distinct latent contribution in addition to sensible heat capacity.','vanelsen2007','Author PDF p21 Eqs33–34','The effective heat capacity becomes ceff = c + cLf.','Conservative enthalpy discretization for a moving source.','Does not supply current numerical4666.67 or establish unequal global branch effects. Different latent temperature distribution.','Put cite on general ceff statement; derive cpeff=cp+L fprime and L/(Tl-Ts) here. Percentages remain computed results.')
add('C10','storage-based interpretation',324,'Observed solidification cooling can slow as latent heat of fusion is released.','hooper2018','Published PDF p11/journalp558 §3.4, Figure14 discussion','The cooling rate slows as solidification begins and heat stored as latent heat of fusion is dissipated.','Two-wavelength100kHz thermography, Ti6Al4V pulsed LPBF,20µm spatial resolution, last hatch/overhang pulses.','Different alloy and transient pulse histories. Qualitative mechanism evidence, not confirmation of current cp sensitivity or time.','Use one qualified sentence in storage discussion, distinguishing precedent from this model-derived moderation.')
add('C11','relative sensitivities could differ',324,'Latent effects depend on transport conditions; small total-energy fraction need not imply small local phase-interval storage.','vanelsen2007','Author PDF pp22–24 Figure7,Eqs39,Conclusion','The length of the melt pool can change significantly due to the latent heat of fusion for high Peclet numbers. [...] For TiAl6V4, the effect of the latent heat is rather small, except for the case when the conductivity is very low.','Ti6Al4V, example40W,0.05m/s, k7W/mK; Gaussian phase interval; enhanced illustrative latent heat in Figure7.','Figure7 uses artificially high latent heat2.92MJ/kg for demonstration; actual Ti64 latent292kJ/kg. Must not borrow quantitative effect or claim universal latent dominance.','Retain direct cite with explicit material/regime qualification if comparing, otherwise cite narrowly at sensitivity conditionality.')
add('C12','High-temperature property measurements provide a route',351,'Ni-superalloy thermophysical predictions at high T require measured or composition-dependent estimated data and carry phase/microstructure limits.','mills2006','Published PDF p1/journal623 Intro; p5/journal627 §7.4; p7/journal629 §9.3–9.4/Figure13','It should not be taken as a substitute for actual measurements. [...] For the liquid alloy [...] k can be calculated [by alternate procedures]. [...] Uncertainty in the calculated [liquid] k values will be >±10%.','Composition-based Ni-superalloy estimates intended for solidification/casting; includes IN625 k(T) Figure13, liquid estimates with limited data.','Not a posterior uncertainty for this study; >±10% pertains their estimated liquid k, not LL/HH scenario spread. Different phase transformations and composition dependence.','Add cite to first high-T uncertainty statement; use IN625 Figure13 as closer property-source route and retain IN718 measurement example separately.')
add('C13','Hosaeus et al.',351,'Fast resistive heating can determine solid/liquid storage and estimate conductivity from resistivity.','pottlacher2001','Complete indexed abstract; no fulltext page claimed','Time resolved measurements with submicrosecond resolution allow the calculation of the specific heat [...] in solid and liquid phase. Thermal conductivity is estimated from resistivity data by the Wiedemann-Franz law at the end of the solid phase and at the beginning of the liquid phase.','Wire-shaped IN718, capacitor-discharge heating; quasistatic DSC and dilatometry comparisons.','Abstract-only source here. No exact heating rate, uncertainties, equations, range or measured liquid-k values may be added. First author is Hosaeus.','Existing cautious Methods description matches abstract; explicitly mark abstract scope in internal ledger, do not claim full-text review. No numerical substitution for IN625.')
add('C14','passage time is a coordinate transformation',159,'Using constant scan speed to transform spatial temperature differences into time-rate change is used in the same AMMT measurement line.','lane2020','Full-text §2.3 P31–34, Eq6 context; P42; ConclusionP69–70','The time-rate change is then calculated using the known constant scan speed v=Δx/Δt. [...]1290°C to1190°C was selected [...] Cooling rate measurements are only provided for comparison, but not recommended for reference or calibration of AM models.','Bare IN625 AMMT/CBM thermal images; radiance/true-temperature mapping, below-solidus interval.','Supports constant-speed mapping; their endpoint/observation differs. It does not validate current1350–1290°C mushy cooling time.','Cite immediately after mapping context; label current ell/v,ΔT/τ and mean axial gradient as derived quantities with independent-thermal-validation limit.')
add('C15','Spatial phase structure and material time',330,'Interface velocity and temperature gradients can depart from steady straight-source estimates when scan pattern/transients matter.','Plotkowski2017Rapid','Author PDF pp18–20 §3, Figure11/Eq4; p25 §5','When the melt pool encompasses many lines [...] the solid-liquid interface velocity is not proportional to the beam velocity, but rather, to the effective velocity of the melt pool in the hatch direction.','Transient ring-source semi-analytical conduction; AlSi10Mg laser and preheated IN718 EBM; constant uniform properties, no latent/flow.','Supports limit on extending v-based mapping, not a failure of current straight-track kinematic relation. Reported validation is grain/CET trend via IN718 EBSD, not accurate temperature history.','Add a concise limitation sentence after current quasi-steady mapping; avoid claiming instantaneous normal solidification speed equals v.')
add('C16','The trajectory represented by a thermal history',335,'Fluid trajectories can experience thermal histories differing from stationary-material passage through a conduction field.','Hou2024Dissolution','Published PDF pp9–10 §4.3, Figures13–14; AppendixC p21','First, for trajectories near the surface, the peak [...] is narrower due to rapid acceleration [...] Second, trajectories underneath the surface experience higher temperatures in CFD because of heat redistribution via convection as well as depression [...] vapor recoil pressure.','Ni-20Cr+Y2O3 ODS, Flow-3D heat/mass/momentum/free-surface/recoil/latent/Marangoni,140W,1.2m/s,20µm beam radius; reduced Eagar–Tsai histories empirically scaled to CFD.','Neither IN625 nor a direct thermal validation; scaling is fitted to CFD and then oxide sizes compared to SANS. Does not prove this rear centerline span is fluid residence.','Retain existing precise Discussion paragraph; citation supports trajectory distinction, no current formula attributed to Hou.')
add('C17','Kollmannsberger et al. provide the closer',310,'Same-benchmark source/model choices affect geometric fit and do not establish internal temperature validity.','kollmannsberger2019','Author preprint p9 Tables7–8/§4.3; p10 Tables9–10/Conclusion','No further calibration is possible as there is only one parameter to calibrate but three values of interest to fit [...] [anisotropic]6.49% [...] it is not valid to predict the temperature distribution within the melt pool.','AMMT IN625 measured beam, scalar eta then directional factors at B and fixed A/C.','Prior isotropic residual is narrower/deeper, whereas current residual is wider/shallower. Opposite shape pattern prevents a shared mechanism assignment or controlled ranking.','Retain citation but mention differing residual direction/source/phase if discussing mechanisms; closest original supports conditional geometry, not exact match to this model.')
add('C18','A length calibration constrains the combination',306,'Geometrically similar parameter choices can produce different temperature profiles in an AM thermal-flow model.','myers2023','Published PDF p9 Figure8 caption and §4.1 context','The four combinations of simulated accommodation and Fresnel coefficients shown had the best agreement to ex-situ geometry measurements(<20%).','Bare316L FLOW-3D six process cases, cross-section area/aspect fitting, two-color surface profiles.','This is geometry-temperature ambiguity under defined fitted parameters, not mathematical forward nonuniqueness nor evidence of equally refitted continuation branches here.','Place cite at general calibration/temperature statement in Discussion only where it performs this precise role; own residual numbers need own table.')
add('C19','source choice a substantive alternative',338,'A dynamic effective volumetric source calibrated over spot-size variation supplies a viable source alternative in IN625.','dynamic2024','Author PDF pp17–18 §2.4–2.5 and p20 Table2','195 W and800mm/s [...] spot diameter(D4σ) [...]80 to322µm [...] [second case]NISTAMB2018-01 [...] eutectic reaction at1410K according to Gulliver-Scheil calculations.','IN625 bare-plate EOSmulti-spot calibration then complex bridge layer transfer; Bayesian/surrogate source k/m calibration.','Different dataset,power,phase properties,source,observers. Cannot rank against present threeAMB2018-02 tracks or use Table2 values as matched measurements.','Retain citation exactly at source alternatives; explicitly list differing eutectic/phase assumptions when relevant to thermal interpretation.')

derived=[
 dict(id='D01',anchor='Equation(frame)',expression='xi=x-vt; ∂tH=-v∂xiH; u=(-v,0,0); div(uH-kgradT)=0',status='derived_in_this_study',limits='Constant v and quasi-steady field; no solved melt-flow velocity.'),
 dict(id='D02',anchor='Gaussian radius/full-plane source',expression='For q∝exp(-2r²/w²), marginal variance σ²=w²/4, so D4σ=4σ=2w; w=85µm. Full-plane integral=etaP; symmetry half=etaP/2.',status='derived_in_this_study',limits='Circular ideal Gaussian, not measured 2D AMMT profile. Dynamic2024 supports convention, lane2020 measured diameter.'),
 dict(id='D03',anchor='latent addition/effective cp',expression='dH/dT=rho[cp+L fprime]; in linear phase interval cpeff=cp+L/(Tl-Ts), latent increment=280000/60=4666.67J/(kgK).',status='derived_in_this_study',limits='Adopted fixed linear phase law; no independent latent ablation.'),
 dict(id='D04',anchor='Equation(passage)',expression='At fixed laboratory point dxi/dt=-v, dT/dt=-v∂xiT. Monotone rear crossings imply τm=ellm/v; Gbar_x=(Tl-Ts)/ellm; cooling magnitudebar=vGbar_x.',status='derived_in_this_study',limits='Axial interval-mean gradient, not vector|gradT| or normal solidification velocity; not fluid-parcel trajectory.'),
 dict(id='D05',anchor='baseline-anchored finite effects',expression='delta_k,delta_cp,I and joint decomposition are algebraic finite contrasts of four deterministic outputs.',status='defined_in_this_study',limits='No external provenance or statistical factorial inference claimed.'),
 dict(id='D06',anchor='selected outward flux counterexample',expression='qdiff=-kgradT; integrated selected boundary depends on k, gradients, surface normals and changing selected region.',status='model_diagnostic_and_mathematical_interpretation',limits='Own retained flux and selection establish counterexample; no literature citation can establish its sign.'),
]

ledger=dict(task='R3_CITATIONS',date='2026-10-01',frozen_manuscript='../manuscript-input.tex',scope='Sentence-level equations, material provenance, transport/storage, thermal-time mapping and source/observation alternatives; no PDE solves or shared-state edits.',sources=sources,support=claims,derived=derived,rejected=[dict(candidate='Coleman2024 DOI supplied in dispatch',doi='10.1016/j.addma.2023.104011',finding='Encoded Crossref DOI endpoint404; OpenAlex exact DOI filter count0; OSTI query empty. Do not cite.',countercheck='2024.104011 resolves to unrelated Liu et al. NiTi Gyroid minimal surface paper; correcting year alone is invalid.',evidence=['metadata/coleman2024fixed-openalex.json','metadata/coleman2024-corrected.json'])],searched_but_not_promoted=[dict(doi='10.1080/00325899.2020.1805547',title='Thermal property measurements of metal injection moulded Inconel625 and Inconel718 using combined thermal analysis techniques',reason='Indexed abstract: MIM solid properties only to1000–1200°C; no OA original discovered. Different processing state and does not bridge current liquid-property gap; not added for citation count.',metadata='metadata/in625thermal2020-openalex.json')],bibliography_additions='None needed: all promoted keys already exist in bibliography-r2.bib. Existing source deep-reading provides more direct support without citation padding.',remaining_gaps=['Composition/state-matched IN625 liquid sensible cp and k are not measured by supplier source. Mills estimates and IN718 rapid-heating abstract cannot decide LL versusHH.', 'Actual nonequilibrium freezing path and latent law of AMMTcoupon not known; Coleman shows an alternative1410K eutectic endpoint.', 'No independent temperature trajectory over1350–1290°C on current tracks; current τ and cooling are dependent field diagnostics.', 'Branch-specific submicrometre geometry precision cannot be created by citations.'])
(ROOT/'support-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2),encoding='utf-8')
print(f'Wrote {len(sources)} source records, {len(claims)} sentence support entries and {len(derived)} derived/own-result entries.')
