"""Produce an evidence-use ledger, retaining actual access and read boundaries."""
import json
import pathlib
import re
import html

ROOT = pathlib.Path(__file__).resolve().parent
PAPER = ROOT.parent.parent
ORIGINAL_KEYS = re.findall(r"@\w+\{([^,]+),", (PAPER / 'literature/bibliography.bib').read_text(encoding='utf-8'))
NEW_DOIS = json.loads((ROOT / 'candidate-dois.json').read_text(encoding='utf-8'))

# support; limits; manuscript use; directly inspected scope
DATA = {
'lane2020': ('AMMT length/cooling and cross-sectional measurement definitions, sampling and uncertainty.', 'Radiance-length front/rear rules differ from two solidus crossings; cooling exemplars are not calibration data. Separate populations and uncertainty budgets.', 'Methods observation operators; Results geometry comparison; Discussion material-time interpretation.', 'Prior direct full HTML §§2–5, documented with paragraph ranges and official source identity in ../../literature/exemplar-notes.md. No local original-text path is asserted here.'),
'kollmannsberger2019': ('Nonlinear temperature/phase-change conduction can reproduce AMMT geometry with measured input and effective directional conductivity; scalar eta alone is insufficient for all geometry in its stated model.', 'Its anisotropic closure and source differ from the current isotropic circular Gaussian. Authors explicitly do not establish internal temperature validity.', 'Introduction existing geometry solutions; Methods benchmark lineage; Discussion shape discrepancy and competing closure/source choices.', 'Prior direct author-preprint §§2–5, particularly §4.2–4.3 pp8–10 Tables7–10; documented original notes.'),
'vanelsen2007': ('Moving-source analytical and nonlinear enthalpy formulations; source representation and material-property effects need separate treatment.', 'Analytical solutions require constant properties/semi-infinite assumptions. Ti64 latent response is not an IN625 quantitative result.', 'Introduction computational hierarchy; Methods moving-frame and enthalpy formulation; Discussion conditional latent contribution.', 'Prior direct author-preprint §§2–5, pp4–6 and16–24; equations32–35 in original notes.'),
'vanini2024': ('Candidate: alternatives to heat-source calibration.', 'Title/metadata only in this worker return. Do not use title as proof of calibration-free accuracy or generality.', 'Hold pending direct substantive reading by journal/coordinator.', 'Verified DOI and Crossref/OpenAlex identity only; public metadata no abstract.'),
'ross2022': ('An inverse heat-conduction procedure fits double-ellipsoid heat-source parameters from solidification-boundary temperatures; trends allow interpolation to intermediate power/speed.', 'Published abstract only. Calibration incorporates effective absorption/vapour penetration, not identification of intrinsic eta or proof for the present source.', 'Introduction successful calibrated-source route; Discussion a source-based alternative to changing conductivity.', 'Full scholarly abstract reconstructed from OpenAlex inverted index on1October2026; no fulltext learning claim.'),
'myers2023': ('Geometry-fitting parameter combinations can produce different thermal profiles; two-colour measurements offer an additional discriminating observable.', 'Already establishes this observation. Its FLOW-3D/source/surface and instrument assumptions differ; no universal mathematical forward nonuniqueness follows.', 'Introduction central precedent; Discussion independent thermal data and limitations.', 'Prior direct version-of-record Intro, Methods, Results, Discussion and Conclusion pp1–10; figure8 p9. Original notes retain links.'),
'hooper2018': ('Two-wavelength thermography measures spatial and temporal thermal histories relevant to gradients/cooling, with explicit instrument calibration.', 'Close-band emissivity assumption, registration, plume/angle/reflection/noise remain. Ti64 and scan-turn transients differ from current quasi-steady bare IN625.', 'Introduction importance of thermal interpretation; Discussion independent measurements and spatial-versus-material time.', 'Prior direct version-of-record §§2.1–2.6 and3.4–3.6 pp2–4,10–12; figures13–14.'),
'liu2024': ('Candidate: scalable path-level thermal history and image validation.', 'Title/metadata only in this worker return; do not claim exact validation protocol from title.', 'Hold pending substantive journal/coordinator reading.', 'Verified DOI and Crossref/OpenAlex identity only; no public abstract returned.'),
'fipy2009': ('FiPy as the finite-volume Python PDE implementation.', 'Software citation supports implementation lineage; it does not verify this discretization or validate physical temperatures.', 'Methods implementation.', 'Existing verified software citation and implementation record; not counted as a scientific-method exemplar.'),
'scipy2020': ('SciPy numerical algorithms used by the implementation.', 'Software pedigree does not replace numerical or physical checks.', 'Methods interpolation/root finding/implementation as applicable.', 'Existing verified software citation and implementation record; not a fulltext research exemplar.'),
'oberkampf2002': ('Numerical verification and physical validation answer different questions.', 'General CFD methodology, not an LPBF accuracy tolerance or certification of this calculation.', 'Methods verification and Discussion limits.', 'Existing verified methodological source from original dossier; scope restricted to standard verification/validation distinction.'),
'specialmetals625': ('Supplier typical IN625 density/melting range and solid-state cp/k tables; cp endpoint1093°C and k endpoint982°C are below adopted solidus.', 'cp is calculated; k is measured for specified annealed material; typical values are not specifications or measured liquid functions for this coupon.', 'Methods property provenance and continuation figure; Discussion closure uncertainty.', 'Prior direct August2013 bulletin pp1–2 Tables2–3; source link in original bibliography and notes.'),
'nist2018': ('Official AMB2018-02 width/depth class means and SDs.', 'Class SD, individual measurement estimate and Lane expanded U(k=2) are different quantities/populations.', 'Methods references/populations; Results shape comparison.', 'Prior direct official current page §2 Table2,1October2026; created2018/updated2025.'),
'lane2020absorption': ('Direct unreflected-power/absorption and morphology evidence distinguishes dynamic, integrated and ex-situ observables.', 'Unreflected power includes plume and mass-energy pathways; reflection alone does not isolate substrate heating. Different spot/power/speed from current case.', 'Introduction absorption-observation route; Discussion fitted eta and alternate causes.', 'Prior direct version-of-record Intro/Methods/Results/Discussion/Conclusion pp1–12; §§2.2,3.2.1,4 especially pp4–5,9–11.'),
'rosenthal1946': ('Moving-source heat-flow solutions and cooling-time/rate predictions are established foundations.', 'The historical abstract concerns welding/metal treatment and steel conditions, not near-source finite-Gaussian LPBF temperature accuracy.', 'Introduction analytical conduction lineage or Methods moving-source context.', 'Complete Crossref/OpenAlex scholarly abstract; no original fulltext inspected. Archive journal field retrospectively differs from original Transactions of ASME.'),
'goldak1984': ('Candidate: double-ellipsoid welding source foundation.', 'Metadata only; no source details imported. Current model is a surface Gaussian.', 'Hold; optional lineage only after reading.', 'Crossref/OpenAlex identity only.'),
'debroy2018': ('Candidate broad process-structure-property review.', 'Metadata only; do not count as read background or substitute for directly read King/Sarkar.', 'Hold; broad review is optional, not indispensable.', 'Crossref/OpenAlex identity only.'),
'king2015': ('LPBF spans coupled physical, material and computational scales; geometry and thermal histories have process-structure roles.', 'Review/context, not proof of the present closure or quantitative accuracy.', 'Introduction affordable models and thermal interpretation; Discussion omitted physics.', 'Author manuscript PDF pp3–6 abstract/Introduction; rest of55pages not claimed read.'),
'khairallah2016': ('High-fidelity powder-resolved models connect recoil/Marangoni/radiative/evaporative physics with melt flow and pores.', 'Read author manuscript uses earlier title/three-author cover; final DOI has four authors. Powder316L and direct rays differ from bare IN625. Does not diagnose this residual.', 'Introduction high-fidelity route; Discussion source/flow/evaporation alternatives.', 'Author-manuscript PDF p3 abstract and pp5–7 Introduction/physics, including no reflection tracking and35µm powder assumption; final metadata separately verified.'),
'matthews2016': ('Powder denudation depends on vapour flux, gas-driven entrainment and pressure; experiments constrain mechanisms.', 'Full abstract only; powder/gas mechanism absent from bare-plate study and cannot explain its residual without evidence.', 'Discussion only if situating powder generalization boundary.', 'Complete Crossref/OpenAlex scholarly abstract; no fulltext.'),
'trapp2017': ('Calorimetric effective absorption depends on power, regime and powder/bare conditions.', 'Full abstract only; measurements on316L/Al/W cannot provide actual IN625 eta. Do not equate fitted model eta with material absorptivity.', 'Introduction source-calibration burden; Discussion eta meaning.', 'Complete Crossref/OpenAlex scholarly abstract; no fulltext.'),
'simonds2018': ('Time-resolved optical coupling and calorimetry can differ because of mass loss; calibrated independent input/output data aid model assessment.', '10ms stationary316L spot weld, not current moving-track conditions. Source is an author arXiv manuscript, not a studied publisher layout.', 'Discussion energy coupling and measurement distinction.', 'Author manuscript PDF pp1–3 abstract/Introduction; direct instrumental claim bounded to that text.'),
'cunningham2019': ('Synchrotron imaging directly observes vapour-depression/keyhole sequence and power-density-dependent transition.', 'Scholarly abstract only. No regime label for current AMMT case is inferred. Crossref editor précis is not used as scientific abstract.', 'Discussion potential omitted free-surface physics; broader Introduction route if needed.', 'Complete scholarly OpenAlex abstract reconstructed and read; fulltext not inspected.'),
'martin2019': ('X-ray experiments plus high-fidelity model connect laser turn-around transients to pore formation.', 'Ti64 transient turn-around, unlike this steady straight-track field; no causal transfer to current width/depth residual.', 'Discussion scope of quasi-steady and omitted transients, only if needed.', 'Version-of-record PDF pp1–2 abstract/Introduction; remaining8pages not claimed read.'),
'king2014': ('Candidate historical keyhole observation.', 'Metadata only. Use directly read Cunningham abstract/Khairallah text for bounded physics context instead.', 'Hold; not indispensable.', 'Crossref/OpenAlex identity only.'),
'rubenchik2018': ('Eagar–Tsai conduction scaling in normalized energy and dwell/diffusion time can organize cross-material dimensions and reduce computation.', 'Neglects flow, evaporation, surface tension and powder; empirical collapse is conditional and later Naderi finds important limits.', 'Introduction fast-model successes; Discussion need for case-specific diagnostics.', 'Accepted-manuscript PDF pp4–7 abstract and Introduction/scaling scope; no whole-paper read claim.'),
'bertoli2017': ('Candidate energy-density limitations.', 'Metadata only; title is not evidence. Current paper need not make a broad VED claim.', 'Hold; exclude from active prose.', 'Crossref/OpenAlex identity only.'),
'ye2019': ('Absorption and melt-depth scaling couple laser conditions, material response and geometry across studied alloys.', 'Author manuscript title/version differs from final journal title; empirical scaling is not independent eta truth for this coupon. Later limits in Naderi/Hong apply.', 'Introduction measured/scaled coupling route; Discussion calibrated or correlated absorption.', 'Complete Crossref abstract and author manuscript PDF p3–4 abstract/Introduction start; final metadata verified separately.'),
'mills2006': ('Composition-based estimates of thermophysical properties help where experiments are unavailable, including liquid/phase concerns.', 'Authors explicitly do not present estimates as a replacement for measurement. Alloy-composition estimates are not current IN625 coupon properties.', 'Methods/Discussion property provenance and cheaper alternative to full new measurement.', 'Version-of-record J-STAGE PDF pp1–2 abstract/Introduction; remaining8pages not claimed read.'),
'pottlacher2001': ('Fast resistive heating measures solid/liquid enthalpy/cp; conductivity can be estimated via resistivity/Wiedemann–Franz.', 'Actual first author is Hosaeus. IN718, not IN625; no numerical substitution for current liquid functions.', 'Discussion feasible high-temperature evidence routes, if needed.', 'Complete scholarly Crossref/OpenAlex abstract; no fulltext.'),
'promoppatum2017': ('FE and Rosenthal can both reasonably estimate IN718 geometry within studied conditions, while differing in absorption sensitivity and high-input shape.', 'Full abstract only; qualified success prevents a strawman claim that analytical/conduction models always fail. Microstructure result not replicated here.', 'Introduction successful affordable models; Discussion source/loss assumptions.', 'Complete Crossref/OpenAlex scholarly abstract; no fulltext (public PDF403).'),
'coen2022': ('Candidate methodological validation of analytical pools.', 'Metadata only; details can change gap appraisal, not current measured evidence.', 'Hold pending targeted access; optional because other analytical-validation sources are usable.', 'Crossref/OpenAlex identity only.'),
'whalen2021': ('An adapted Eagar–Tsai model includes temperature-dependent/powder properties, infers apparent absorption/porosity distributions and propagates depth uncertainty.', '316L; input distributions fitted to geometry are effective parameters. External printability comparison is qualitative with different ratio thresholds; not internal thermal validation.', 'Introduction prior property/uncertainty treatment; Discussion distinction from deterministic continuation scenarios.', 'Author-manuscript PDF pp1–4 abstract/Introduction,pp7–8 model properties/powder,pp19–20 external comparison/Conclusion.'),
'naderi2023': ('Scaling-law fidelity depends on material and regime; revised separate regime fits improve studied depth errors.', 'Not a universal condemnation of thermal conduction. Revised fits and multi-alloy depth data do not examine current local nonlinear cp/k continuations.', 'Introduction known regime/transfer limits; Discussion no cross-condition ranking.', 'Version-of-record PDF pp1–2 Intro/abstract,p5 measurement conditions,pp13–14 Conclusions; print2023 vs online2022.'),
'bayat2019': ('High-fidelity ray-reflection/free-surface flow model plus XCT validates keyhole-porosity mechanisms in Ti64.', 'Uncorrected proof, powderTi64; scope differs. No current residual/keyhole label follows.', 'Introduction physically richer route; Discussion alternate physics.', 'Uncorrected-proof PDF pp1–2 abstract/Introduction; no complete numerical method read claim.'),
'weaver2024': ('AMBench2022 provides controlled IN718 track/pad geometry, uncertainties and heat-buildup effects.', 'Different year/material/dataset; cannot supply AMB2018IN625 statistics or repair Hong dataset identity.', 'Methods benchmark lineage or Discussion future multi-observable controlled measurements.', 'Complete Crossref/OpenAlex scholarly abstract; no fulltext (PMC request403).'),
'yang2024': ('Analytical LPBF models have already quantified k/cp and source/laser sensitivity of thermal/geometry outputs.', 'Constant-property Ti64; one-factor changes and radar weighting are not nonlinear high-temperature four-corner closure interactions. Some extreme peak values and a unit typo must not be imported as physical truth.', 'Introduction direct material-sensitivity precedent; Discussion scope of our independent closure decomposition.', 'Version-of-record18pp PDF: abstract/Intro1–2; methods3–6; sensitivity9,12–15; Conclusion16.'),
'soares2026': ('Thermal-camera and post-process comparisons expose different agreement for surface and depth; high correlation can coexist with biased scale.', 'Analytical Gaussian fixed0.8Tmelt properties, powder corrections and no explicit phase change. Camera calibration uses melting/metallography; not wholly independent temperature truth. Proposed depth correction is not prospective validation.', 'Introduction recent reliability assessment; Discussion observation/shape discrepancies and correlation versus agreement.', 'Version-of-record27pp PDF §§2.1 pp3–6;3.2 pp12–13;3.2.2p17;3.3pp17–18;Discussion18–21;Conclusion21–22.'),
'hong2026': ('A recent fitting-free diagnostic asks whether an Eagar–Tsai conduction model requires physically infeasible absorption to explain measured depth; sensitivity/effective-diffusivity controls test robustness.', 'Effective/constant-property231bare tracks across datasets; IN625 empirical absorption and data-label concern require caution. Does not examine our nonlinear high-T functions or rear Ts/Tl split. Its mechanism inference cannot be transferred.', 'Introduction direct diagnostic overlap; Discussion controls needed before attributing conduction-model discrepancy.', 'Version-of-record21pp PDF Intro1–3;Methods2.1–2.4pp4–7;robustness3.4pp12–13;correction3.5p14;Discussion16–18;Conclusion18;refs20–21.'),
'solidpath2024': ('Critical candidate: alloy solidification path and melt-pool response.', 'Metadata only; do not claim lack of related latent/solidification analysis. This limits breadth/priority of novelty claim.', 'Hold; scientific question recorded in research-line.md.', 'Crossref/OpenAlex identity only; parent handled one targeted publisher session.'),
'jmapro2024': ('Close IN625 candidate: processing parameters and melt-pool characteristics.', 'Metadata only; not evidence of our exact continuation design or absence of overlap.', 'Hold; gap-impact question in research-line.md.', 'Crossref/OpenAlex identity only; parent public/session access queue.'),
'heatsourcebayes2024': ('Four source models were compared through fusion-zone errors and Bayesian optimization; a calibrated conical-source regression transfers across a studied process window.', 'IN738LC; calibration still occurs during model construction. Cross-sectional agreement and reported LOOCV do not prove thermal histories or all-material validity. Conical source cannot be ranked against current Gaussian across unlike cases.', 'Introduction successful source-calibration/transfer route; Discussion source alternative and comparison design.', 'Version-of-record17pp PDF pp1–2 Intro/abstract,p4 calibration/Methods,pp15–16 Conclusions. Reported source ranking restricted to its experiment.'),
'dynamic2024': ('A dynamic two-parameter volumetric source adjusts depth/absorption and improves IN625 geometry across a calibrated spot-size range; local dynamic conditions motivate source transfer.', 'Bare-plate EOSmulti-spot195W/800mm/s then AMB2018-01 layer case, not our threeAMB2018-02 targets. Table2 uses different phase-dependent k/cp and eutectic1410K, not our solidus. Effective source success cannot validate internal temperatures.', 'Introduction successful calibrated-source route; Discussion source/closure alternatives and a future discriminating comparison.', 'Author manuscript45pp PDF pp1–6 Intro/model;pp17–20 calibration/problem/materials;pp39–40 Discussion/Conclusions. Final journal identity separately verified.'),
'gasliquid2025': ('Recent multiphase modelling connects spatter/entrainment and tail-flow perturbations with possible defects.', 'Full abstract only; powder mechanisms are not present in this bare-plate study and are not a cause assigned to its thermal tail.', 'Discussion boundary on extension to powder; optional citation only.', 'Complete Crossref/OpenAlex scholarly abstract; public repository PDF403.'),
'feedforward2025': ('Candidate vector-level thermal model control.', 'Metadata only; no algorithm/validation claims. Optional to present paper, not a dependency.', 'Hold; no active prose.', 'Crossref/OpenAlex identity only.'),
'weeks2026': ('An observation model for internal thermal-emission reflections can reconcile some simulated/camera discrepancy.', 'Full abstract only here;316L concave keyhole, not a universal correction or matched AMMT sensor. Changes observation mapping, not necessarily thermal physics.', 'Introduction observation-aware assessment; Discussion camera-to-field mapping.', 'Complete scholarly OpenAlex abstract from prior search; version-of-record fulltext/format not read by this worker.'),
'review2024': ('Recent review describes FEM model hierarchies, material-temperature dependence and thermal/structural coupling.', 'Broad FEM/part-scale review and journal pre-proof; equation forms are illustrative and not imported without independent derivation.', 'Introduction computational tradeoff or Discussion material-data requirements, with primary sources for detailed claims.', 'Journal-pre-proof84pp PDF p2 abstract,pp16–18 material properties/thermal equations; remaining66pages not claimed read.'),
}

HOLDS = {'vanini2024','liu2024','goldak1984','debroy2018','king2014','bertoli2017','coen2022','solidpath2024','jmapro2024','feedforward2025'}
RETRIEVED = json.loads((ROOT / 'retrieval-records.json').read_text(encoding='utf-8'))
RETRIEVED_BY_KEY = {x['key']: x for x in RETRIEVED}
ALIASES = {'yang2024':'sigler2024', 'soares2026':'reliability2026', 'hong2026':'fittingfree2026'}
records = []
abstracts = []
for key in ORIGINAL_KEYS + list(NEW_DOIS):
    support, limits, use, scope = DATA[key]
    rec = {'key': key, 'status': 'hold_metadata_only' if key in HOLDS else 'usable_with_scope', 'support':support, 'limits_counterevidence':limits, 'point_of_use':use, 'read_scope':scope}
    rec['identity_sources'] = ['../../literature/bibliography.bib'] if key in ORIGINAL_KEYS else [f'metadata/{key}-crossref.json',f'metadata/{key}-openalex.json']
    if key in NEW_DOIS: rec['doi'] = NEW_DOIS[key]
    if key in {'vanini2024','liu2024','ross2022'}: rec['identity_sources'] += [f'metadata/{key}-crossref.json',f'metadata/{key}-openalex.json']
    pdfkey = ALIASES.get(key,key)
    if (ROOT/'pdfs'/f'{pdfkey}.pdf').exists():
        rec['local_fulltext'] = f'pdfs/{pdfkey}.pdf'
        rec['local_extraction'] = f'text/{pdfkey}.txt'
    if pdfkey in RETRIEVED_BY_KEY: rec['retrieval'] = RETRIEVED_BY_KEY[pdfkey]
    if key in ORIGINAL_KEYS: rec['prior_read_evidence'] = '../../literature/exemplar-notes.md'
    records.append(rec)
    if key not in HOLDS:
        for provider in ['crossref','openalex']:
            p=ROOT/'metadata'/f'{key}-{provider}.json'
            if not p.exists():continue
            raw=json.loads(p.read_text(encoding='utf-8'))['response'];raw=raw.get('message',raw)
            a=raw.get('abstract')
            inv=raw.get('abstract_inverted_index')
            if inv:
                z={i:w for w,indices in inv.items() for i in indices}
                a=' '.join(z[i] for i in sorted(z))
            if a:
                a=html.unescape(re.sub('<[^>]+>','',a))
                # Crossref's Cunningham précis is editorial, not the scholarly abstract.
                if key=='cunningham2019' and provider=='crossref':continue
                abstracts.append(f'## {key} — {provider}\n\nSource: [{p.name}](metadata/{p.name}). DOI: https://doi.org/{rec.get("doi","")}\n\n{a}\n')
                break
(ROOT/'source-ledger.json').write_text(json.dumps({'date':'2026-10-01','scope':'This worker literature return; primary evidence and manuscript are unchanged. Usable means only the recorded claim/read scope, not fulltext or validation completeness.','counts':{'identities':len(records),'usable_with_scope':sum(x['status']=='usable_with_scope' for x in records),'hold_metadata_only':len(HOLDS)},'sources':records},ensure_ascii=False,indent=2),encoding='utf-8')
(ROOT/'abstracts.md').write_text('# Actually obtained metadata abstracts\n\nFulltext notes and limitations take priority over abstract claims. Some fulltext sources have no metadata abstract. The Cunningham record uses its scholarly OpenAlex abstract, not the Crossref editor précis. Simonds has a truncated Crossref abstract; use the directly read complete PDF abstract instead.\n\n'+'\n'.join(abstracts),encoding='utf-8')
lines=['# R2 citation map','', 'The bibliography retains 47 verified identities: 37 have an immediate, bounded use and 10 are held as metadata-only candidates. This is a research-use map, not a instruction to cite every entry. Existing14keys are preserved verbatim. Reading of the original set is documented in the [original exemplar notes](../../literature/exemplar-notes.md); new retrieval and selected-page reading are recorded in [source-ledger.json](source-ledger.json). No inferred citation minimum is treated as a journal requirement.','', '## Paragraph-level use','', '- Introduction paragraph1: king2015, hooper2018, myers2023 — process relevance and the need to interpret thermal conditions.','- Introduction paragraph2: rosenthal1946, vanelsen2007, rubenchik2018, promoppatum2017, kollmannsberger2019 — established affordable models, their useful successes and conditions.','- Introduction paragraph3: ross2022, whalen2021, heatsourcebayes2024, dynamic2024 — successful calibrated-source, uncertainty and transfer strategies. Do not imply that fixed calibration cannot ever transfer.','- Introduction paragraph4: myers2023, lane2020absorption, trapp2017, weeks2026 — geometry, effective absorption and observation mapping carry different information.','- Introduction paragraph5: yang2024, soares2026, hong2026, naderi2023 — current sensitivity/reliability/diagnosis work. The increment is narrower than “material sensitivity” or “conduction breakdown.”','- Introduction closing: this study design/results, supported by the existing evidence dossier; specialmetals625 supplies the actual property-table limits. Do not attach literature citations as if those papers produced our values.','- Methods: lane2020, nist2018, specialmetals625, vanelsen2007, kollmannsberger2019, fipy2009, scipy2020, oberkampf2002 — each with the specific role listed below.','- Discussion: compare current findings with the closestYang/Soares/Hong/Coleman/Whalen precedents; use khairallah2016, cunningham2019, bayat2019, martin2019 only for bounded alternate-physics context. mills2006/pottlacher2001 suggest property-evidence routes; weaver2024 supplies future benchmark design context. Peripheral powder sources matthews2016/gasliquid2025 need only be cited if that extension is actually discussed.','', '## Source-by-source use and boundary','']
for x in records:
    lines += [f'### `{x["key"]}` — {x["status"]}','',f'**Use:** {x["point_of_use"]}', '',f'**Supported point:** {x["support"]}', '',f'**Read scope:** {x["read_scope"]}', '',f'**Limit or counterevidence:** {x["limits_counterevidence"]}', '']
    if x.get('local_fulltext'):lines += [f'Local source: [{x["local_fulltext"]}]({x["local_fulltext"]}); [page-marked text]({x["local_extraction"]}).','']
    if x.get('doi'):lines += [f'Persistent source: https://doi.org/{x["doi"]}','']
(ROOT/'citation-map.md').write_text('\n'.join(lines),encoding='utf-8')
print(json.dumps({'identities':len(records),'usable':len(records)-len(HOLDS),'holds':len(HOLDS),'metadata_abstracts':len(abstracts)}))
